<a href="https://colab.research.google.com/github/Jatingpt/NumPy-/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Numpy**

##NumPy stands for Numeric Python.
##NumPy is a package that defines multidimensional array and assosiate fast math functions.
##Also have the functions working on the domains like- Linear Algebra, Matrices, Sum etc.
##In simple words it is the fundamental package for scientific computation.

##**Advantages of NumPy.**
##NumPy uses less memory to store the data.
##Mathematical operations are faster.
##Can create n-dimensional array.
##Finding elements in NumPy array is easy.

##**Array-**: An array is defined as the collection of items that are stored at contiguous memory location.
##It is a container which can store the fixed number of items of same type of data.

##A combination of array saves a lot time and also can reduce the overall size of the code.

##**Difference between List and Array.**

##A list cannot handle the mathematical operations, while an Array can.

##List can store more data as compare to an Array.

##List can store the multiple types of data while an array can only store the same type of datas.

##Functions and executions of code is faster in an Array as compare to a List.

##A list is easier to modify e.g- Add, Delete than an Array.

##Let's see some examples of a list and an Array with the difference.

In [ ]:
l1 = [1, 2, 3, 4, 5, 6]
l2 = [7, 8, 9, 10, 11]

print(l1 + l2)         #Here the list is doing nothing but concanating two list.

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

b = np.array([7, 8, 9, 10, 11])

print(a)
print(b)
print()

print(a+b)  #Here we can see that instead of concatenation numpy performed a mathematical operations with these two array.



[1 2 3 4 5]
[ 7  8  9 10 11]

[ 8 10 12 14 16]


##**Creation, Indexing and Slicing of NumPy Arrays.**

In [ ]:
import numpy as np

#Creation

#1-D Array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

print()

#2-D Array.
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[1 2 3 4 5 6 7 8 9]

[[1 2 3]
 [4 5 6]]


In [ ]:
#Slicing and indexing of an Array

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)


print(arr[0:4])

print(arr[2:5])

#In 2-D Array
print()
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(a)

print()
print(a[0:2, 0:2])

#If we only wants the element of the first index in the array a then,
print()

print(a[0,1:3]) #Here "0" is the index number and "1:3" is the slicing that we are performing.

print()

print(a[1,0:3])

[1 2 3 4 5]
[1 2 3 4]
[3 4 5]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[1 2]
 [6 7]]

[2 3]

[6 7 8]


##**Attributes of an Array.**

##There are some of the attributes of an Array which helps us to get the data and some information about the array.

##Attributes of an Array- **(a.shape, a.size, a.dim, a.len, a.astype(int), b.dtype etc.)**

In [ ]:
#Attributes-

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

print(len(arr))
print()
print(arr.size)        #Gives number of elements in the array.
print()
print(arr.shape)       #Gives the dimentions of an array in the form of rows and columns.
print()
print(arr.astype)      #for the type of array that we have.
print()
print(arr.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2

10

(2, 5)

<built-in method astype of numpy.ndarray object at 0x7bab00057930>

int64


##**Mathematical functions and operations.**

##Such as Subtraction, Addition, Multiplication etc.

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

print(a+b)

[ 2  4  6  8 10]


In [ ]:
print(np.add(a,b))

[ 2  4  6  8 10]


In [ ]:
print(np.multiply(a,b))

[ 1  4  9 16 25]


In [ ]:
print(np.subtract(a,b))

[0 0 0 0 0]


In [ ]:

arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[1,2],
                 [3,4]])

print(np.add(arr1,arr2))

[[2 4]
 [6 8]]


In [ ]:
print(np.subtract(arr1,arr2))

In [ ]:
print(np.multiply(arr1,arr2))

[[ 1  4]
 [ 9 16]]


In [ ]:
a = np.array([1,2,3,4,5])
b =np.array([2])

print(np.power(a,b))

[ 1  4  9 16 25]


##**Combining and spliting arrays.**

In [ ]:
#In list.

a = [23,45,53,53,23,56]
b = [23,55,23,76,46,76]
print(a+b)

[23, 45, 53, 53, 23, 56, 23, 55, 23, 76, 46, 76]


In [ ]:
#In array- Or can say that concatenation in numpy.
a = np.array([23,45,53,53,23,56])
b = np.array([23,55,23,76,46,76])

print(np.concatenate([a,b]))

[23 45 53 53 23 56 23 55 23 76 46 76]


##**In terms of axis.**

In [ ]:
arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[1,2],
                 [3,4]])

print(np.concatenate([arr1,arr2], axis = 1))

[[1 2 1 2]
 [3 4 3 4]]


##**Or instead of giving axis as the parameter, we can also use the "Stack" method directly. e.g**

In [ ]:
arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[1,2],
                 [3,4]])
print(np.hstack([arr1,arr2]))

[[1 2 1 2]
 [3 4 3 4]]


In [ ]:
arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[1,2],
                 [3,4]])

print(np.vstack([arr1,arr2]))

[[1 2]
 [3 4]
 [1 2]
 [3 4]]


In [ ]:

arr1 = np.array([[1,2],
                 [3,4]])

arr2 = np.array([[1,2],
                 [3,4]])

print(np.concatenate([arr1,arr2]))

[[1 2]
 [3 4]
 [1 2]
 [3 4]]


##**Spliting the values.**

##We can split the values directly or with the help of assigning the variables.

In [29]:
a = [23,45,53,53,23,56]

print(np.array_split(a,3))

print()

b = np.array_split(a,3)
print(b)

[array([23, 45]), array([53, 53]), array([23, 56])]

[array([23, 45]), array([53, 53]), array([23, 56])]


##**Adding and removing elements in the array.**

##Here we are using Append, Insert and Delete method to do the operations.
##Here we are doing the operation on the 1-D array. If we want operations on multiple array then we can do it by axis accrodingly.

In [30]:
a = [23,45,53,53,23,56]

b = [23,55,23,76,46,76]

print(np.append(a,b))

print()

print(np.insert(a,1,7))

print()

print(np.delete(a,1))

[23 45 53 53 23 56 23 55 23 76 46 76]

[23  7 45 53 53 23 56]

[23 53 53 23 56]


##Deleting or adding according to axis.

In [37]:
a = np.array([[1,2],[3,4]])

print(a)

print()

print(np.delete(a,1,axis = 0))

print()

print(np.delete(a,1,axis=1))

[[1 2]
 [3 4]]

[[1 2]]

[[1]
 [3]]


##**Search, sorting and filtering of an array.**

##**search-** Usually there is no functions of search in the numpy instead we can use "Where" Method to search anything in the array.

##**Filter-** It will create a new array from the existing array by filtering the existing array with the help or "True", "False" values.

In [57]:
import numpy as np

#sort

ar = np.array([9,2,4,2,5,7,1])

print(np.sort(ar))

print()

#search= where

print(np.where(ar == 2)) #Here it will give you the indexing of all the elements that we are searching for.

print()

print(np.where(ar ==7))

#Searchsorted

ss = np.searchsorted(ar,7)     #Ck
print(ss)

print()
#Filter- It will create a new array from the existing array.

a = np.array([1,2,3,4])
fa = [True, False, True, False]
new = a[fa]
print(new)

print()

ar = np.array([23,4,53,45])
fa = [True,False,True,False]
new_ar = ar[fa]
print(new_ar)

[1 2 2 4 5 7 9]

(array([1, 3]),)

(array([5]),)
5

[1 3]

[23 53]


##**Aggregating functions in array.**

##i.e- sum, min, max, cumsum(cumulative sum), cumprod(cumulative product).

##**cumsum** is nothing but gives you a fabonacci series of the element.

##**cumprod** will provide the cumulative product of all the previous elements.

In [64]:
import numpy as np
#sum

a = np.array([1,2,3,4,5])
print(np.sum(a))

#min
print(np.min(a))

#max
print(np.max(a))

#cumsum i.e cumulative sum of the array.
print(np.cumsum(a))  #Basically cum sum is nothing but gives you a fabonacci series.

#cumprod i.e cumalative product of the array.
print(np.cumprod(a))

15
1
5
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [81]:
#Another example of the cumprod i.e cumulative product.

a = [10,20,30,40]
b = [1,2,3,4]

price = np.array(a)
quantity = np.array(b)

print(price,quantity)

print()

#print(np.cumprod([price,quantity]))  #It is giving nothing but simply cumprod, so

#print(np.cumprod([price,quantity],axis = 0)) #or also we can assign a variable to this code.

c = np.cumprod([price,quantity],axis = 0)

print(c)

print()

print(c[1].sum())         #if we want sum of the total then.

[10 20 30 40] [1 2 3 4]

[[ 10  20  30  40]
 [ 10  40  90 160]]

300


##**Statistical functions in NumPy.**

In [92]:
food_price = [10,20,30,40,50,60,60]
a = np.array(food_price)
print(np.mean(a))

print(np.median(a))

#print(np.mode(a)) error because numpy has no attribute as mode so, first we have to import stats library in python.

import statistics as stats

print(stats.mode(a))

print(np.std(a))  #Notes about the standard deviation.

38.57142857142857
40.0
60
18.070158058105026


##If the Standard Deviation is greater means the data is far more than the mean value or vice versa.

##**Notes- std gives or providing the difference between the mean value and the spread. If the spread is far from the mean value means there are many fluctuations coming and which is not good. So, if the spread is less so then the product is okay or fine.**



##**Co-Relation or Coefficiant of Co-Relation.**

###(-1) = Represents the inversely or negative proportional relation.

###+(1) Represents the directly proportional relation.

###(0) Represent means no relation at all.

##E.g, If the cunsumption of tobacco is increasing then death increases.


In [94]:
tobacco_cunsumption = [10,20,30,40,50]
num_of_death = [100,159,280,350,480]

print(np.corrcoef([tobacco_cunsumption,num_of_death]))  #Strongly positive

[[1.         0.99284241]
 [0.99284241 1.        ]]


In [98]:
price = [10,20,30,40]
sales = [39,28,18,8]

print(np.corrcoef(price,sales))      #Strongly negative.

[[ 1.         -0.99971734]
 [-0.99971734  1.        ]]


#                                 ----NumPy end-----