<a href="https://colab.research.google.com/github/Jatingpt/NumPy-/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Numpy**

##NumPy stands for Numeric Python.
##NumPy is a package that defines multidimensional array and assosiate fast math functions.
##Also have the functions working on the domains like- Linear Algebra, Matrices, Sum etc.
##In simple words it is the fundamental package for scientific computation.

##**Advantages of NumPy.**
##NumPy uses less memory to store the data.
##Mathematical operations are faster.
##Can create n-dimensional array.
##Finding elements in NumPy array is easy.

##**Array-**: An array is defined as the collection of items that are stored at contiguous memory location.
##It is a container which can store the fixed number of items of same type of data.

##A combination of array saves a lot time and also can reduce the overall size of the code.

##**Difference between List and Array.**

##A list cannot handle the mathematical operations, while an Array can.

##List can store more data as compare to an Array.

##List can store the multiple types of data while an array can only store the same type of datas.

##Functions and executions of code is faster in an Array as compare to a List.

##A list is easier to modify e.g- Add, Delete than an Array.

##Let's see some examples of a list and an Array with the difference.

In [1]:
l1 = [1, 2, 3, 4, 5, 6]
l2 = [7, 8, 9, 10, 11]

print(l1 + l2)         #Here the list is doing nothing but concanating two list.

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [5]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

b = np.array([7, 8, 9, 10, 11])

print(a)
print(b)
print()

print(a+b)  #Here we can see that instead of concatenation numpy performed a mathematical operations with these two array.



[1 2 3 4 5]
[ 7  8  9 10 11]

[ 8 10 12 14 16]


##**Creation, Indexing and Slicing of NumPy Arrays.**

In [9]:
import numpy as np

#Creation

#1-D Array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

print()

#2-D Array.
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[1 2 3 4 5 6 7 8 9]

[[1 2 3]
 [4 5 6]]


In [24]:
#Slicing and indexing of an Array

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)


print(arr[0:4])

print(arr[2:5])

#In 2-D Array
print()
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(a)

print()
print(a[0:2, 0:2])

#If we only wants the element of the first index in the array a then,
print()

print(a[0,1:3]) #Here "0" is the index number and "1:3" is the slicing that we are performing.

print()

print(a[1,0:3])

[1 2 3 4 5]
[1 2 3 4]
[3 4 5]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[1 2]
 [6 7]]

[2 3]

[6 7 8]


##**Attributes of an Array.**

##There are some of the attributes of an Array which helps us to get the data and some information about the array.

##Attributes of an Array- **(a.shape, a.size, a.dim, a.len, a.astype(int), b.dtype etc.)**

In [38]:
#Attributes-

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

print(len(arr))
print()
print(arr.size)        #Gives number of elements in the array.
print()
print(arr.shape)       #Gives the dimentions of an array in the form of rows and columns.
print()
print(arr.astype)      #for the type of array that we have.
print()
print(arr.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2

10

(2, 5)

<built-in method astype of numpy.ndarray object at 0x7bab00057930>

int64
